name: Deploy Prisma Migrations to Production

on:
  push:
    branches:
      - master # Change if your production branch is different

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Prisma Migrate Deploy (if there are new migrations)
        env:
          DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -q prisma/migrations; then
            echo "New migrations found. Deploying..."
            npx prisma migrate deploy
          else
            echo "No new migrations. Skipping deploy."
          fi
